---
- hosts: all
  become: yes
  tasks:
  - name: Install a list of packages for docker
    apt:
      pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"

  - name: Install docker
    apt:
      pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

  - name: Add ubuntu user to docker group
    user:
      name: ubuntu
      groups: docker
      append: yes

  - name: Change docker config for logs
    copy:
      dest: /etc/docker/daemon.json
      content: >
        {
          "log-driver": "json-file",
          "log-opts": {
            "max-size": "10m",    
            "max-file": "3"    
          }
        }

  - name: Restart docker
    service:
      name: docker
      state: restarted

  - name: Install parallel
    apt:
      pkg:
      - parallel 
